/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.inatel.view.boutiqueervadoce;

import br.inatel.controller.boutiqueervadoce.ClienteDAO;
import br.inatel.controller.boutiqueervadoce.FuncionarioDAO;
import br.inatel.model.boutiqueervadoceprojeto.Cliente;
import br.inatel.model.boutiqueervadoceprojeto.Funcionario;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cesar
 */
public class ListarCliente_Funcionario extends javax.swing.JFrame {

    // Variável auxiliar para manipular tabelas
    private DefaultTableModel dtm;

    // Funcionarios
    private FuncionarioDAO fdao = new FuncionarioDAO();

    // Clientes
    private ClienteDAO cdao = new ClienteDAO();

    // ArrayList para ler os funcionarios do banco
    private ArrayList<Funcionario> funcionarios = new ArrayList<>();

    // ArrayList para ler os clientes do banco
    private ArrayList<Cliente> clientes = new ArrayList<>();

    /**
     * Creates new form ListarCliente_Funcionario
     */
    public ListarCliente_Funcionario() {
        initComponents();

        // Fazendo referencia a tabela da view
        dtm = (DefaultTableModel) jTable1.getModel();

        // Lendo os funcionarios e clientes do banco
        funcionarios = fdao.buscarUsuariosSemFiltro();
        clientes = cdao.buscarClientes();

        // Método para atualizar a tabela
        atualizarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        bnt_Buscar = new javax.swing.JButton();
        bnt_Limpar = new javax.swing.JButton();
        bnt_Menu = new javax.swing.JButton();
        lbl_nome = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        lbl_buscar = new javax.swing.JLabel();
        bnt_Excluir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cr_button = new javax.swing.JRadioButton();
        fr_button = new javax.swing.JRadioButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Buscar ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        bnt_Buscar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        bnt_Buscar.setText("Buscar");
        bnt_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_BuscarActionPerformed(evt);
            }
        });

        bnt_Limpar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        bnt_Limpar.setText("Limpar");
        bnt_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_LimparActionPerformed(evt);
            }
        });

        bnt_Menu.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        bnt_Menu.setText("Menu");
        bnt_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_MenuActionPerformed(evt);
            }
        });

        lbl_nome.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl_nome.setText("Nome:");

        txt_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomeActionPerformed(evt);
            }
        });

        lbl_buscar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl_buscar.setText("Buscar por:");

        bnt_Excluir.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        bnt_Excluir.setText("Excluir");
        bnt_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_ExcluirActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Listar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CPF", "Nome", "Sexo", "E-mail", "Cidade", "Rua", "Número", "Estado", "Telefone"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
        );

        buttonGroup1.add(cr_button);
        cr_button.setText("Cliente");

        buttonGroup1.add(fr_button);
        fr_button.setText("Funcionario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 37, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_buscar)
                                .addGap(49, 49, 49)
                                .addComponent(cr_button)
                                .addGap(48, 48, 48)
                                .addComponent(fr_button)
                                .addGap(120, 120, 120)
                                .addComponent(bnt_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_nome)
                                .addGap(18, 18, 18)
                                .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(bnt_Limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(bnt_Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(bnt_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nome)
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(bnt_Buscar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cr_button)
                            .addComponent(fr_button)
                            .addComponent(lbl_buscar))))
                .addGap(28, 28, 28)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnt_Limpar)
                    .addComponent(bnt_Excluir)
                    .addComponent(bnt_Menu))
                .addContainerGap(277, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnt_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_BuscarActionPerformed
        // TODO add your handling code here:
        this.atualizarTabela();
    }//GEN-LAST:event_bnt_BuscarActionPerformed

    private void txt_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomeActionPerformed

    private void bnt_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_ExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnt_ExcluirActionPerformed

    private void bnt_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_LimparActionPerformed
        this.txt_nome.setText("");

    }//GEN-LAST:event_bnt_LimparActionPerformed

    private void bnt_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_MenuActionPerformed
        // TODO add your handling code here:
        ListarCliente_Funcionario busca = new ListarCliente_Funcionario();
        Menu menu = new Menu();
        menu.setVisible(true);
        busca.dispose();
    }//GEN-LAST:event_bnt_MenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarCliente_Funcionario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarCliente_Funcionario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarCliente_Funcionario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarCliente_Funcionario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarCliente_Funcionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt_Buscar;
    private javax.swing.JButton bnt_Excluir;
    private javax.swing.JButton bnt_Limpar;
    private javax.swing.JButton bnt_Menu;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cr_button;
    private javax.swing.JRadioButton fr_button;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_buscar;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JTextField txt_nome;
    // End of variables declaration//GEN-END:variables

    /**
     * Atualiza a Tabela conforme edições.
     */
    public void atualizarTabela() {
        dtm.getDataVector().removeAllElements();
        funcionarios = fdao.buscarUsuariosSemFiltro();
        clientes = cdao.buscarClientes();

        // Se o botão de clientes estiver marcado
        if (cr_button.isSelected()) {
            // Seta a tabela com os atributos de clientes
            for (Cliente c : clientes) {
                dtm.insertRow(dtm.getRowCount(), new Object[]{
                    c.getCpf(),
                    c.getNome(),
                    c.getSexo(),
                    c.getEmail(),
                    c.getCidade(),
                    c.getRua(),
                    c.getNum(),
                    c.getEstado(),
                    c.getTel()
                });
            }
        } else if (fr_button.isSelected()) {
            // Caso seja o botão de funcionarios, seta com os atributos de funcionario
            for (Funcionario f : funcionarios) {
                dtm.insertRow(dtm.getRowCount(), new Object[]{
                    f.getCpf(),
                    f.getNome(),
                    f.getSexo(),
                    f.getEmail(),
                    f.getCidade(),
                    f.getEndereco(),
                    f.getNum(),
                    f.getEstado(),
                    f.getTel()
                });
            }
        } else {
            // Caso nenhum esteja selecionado, deixa a tabela vazia
            dtm.insertRow(dtm.getRowCount(), new Object[]{
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                ""
            });
        }

    }
}
